# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    # This config works only if there aren't workflows
    # branches:
    #   only:
    #     -master
    #     -/feature.*/
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: npm test

      - save_cache:
          paths:
            - coverage
          key: v1-coverage-{{ checksum "package.json" }}
  npm_publish:
    machine:
        enabled: true
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-coverage-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-coverage-
      - run: npm install
      - run:
          name: Set COVERALLS authentication.
          command: 'echo "repo_token: ${COVERALLS_TOKEN}" > ~/.coveralls.yml'
      - run:
          name: Upload coverage
          command: npm run coverage
      - run:
          name: Set NPM authentication.
          command: 'echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc'
      - run:
          name: Publish the module to npm.
          command: npm publish --access=public

workflows:
    version: 2

    build:
      jobs:
        - build:
            filters:
              branches:
                only:
                  - master
                  - /feature.*/
              tags:
                ignore: /^v.*/

    tagged-build:
      jobs:
        - build:
            filters:
              branches:
                ignore: /.*/
              tags:
                only: /^v.*/
        - npm_publish:
            requires:
              - build
            filters:
              branches:
                ignore: /.*/
              tags:
                only: '/^v[\d.]+$/'
